/** 
 * In this class, we test predefined colours. Some are predefined by
 * constants such such as BLACK, RED and so on. They can also be
 * defined by Color(r,g,b) where r,g,b are values between 0 and
 * 255. r=red, g=green, and b=blue. 0,0,0 stands for black, 255,0,0
 * for red, 0,255,0 for green, and 0,0,255 blue with other values in
 * between.
 *
 * @version 2015-11-16
 * @author Manfred Kerber
 */

import java.awt.*;
import javax.swing.JPanel;
import javax.swing.JFrame;

public class Colour extends JPanel{

    /**
     *    Override the paintComponent method from the JPanel class.
     *    Then we write text using the different colours, generated by
     *    the Color(r,g,b) constructor.
     *    @param g The graphics component used for painting.
     */
    @Override
    public void paintComponent(Graphics g){
	Font myfont = new Font("Dialog",1,36);
	setFont(myfont);
	g.setColor(new Color(0,0,0));
	g.drawString("BLACK: Color(0,0,0)", 30, 30);
	g.setColor(new Color(255,0,0));
	g.drawString("RED: Color(255,0,0)", 30, 60);
	g.setColor(new Color(0,255,0));
	g.drawString("GREEN: Color(0,255,0)", 30, 90);
	g.setColor(new Color(0,0,255));
	g.drawString("BLUE: Color(0,0,255)", 30, 120);
	g.setColor(new Color(255,200,0));
	g.drawString("ORANGE: Color(255,200,0)", 30, 150);
	g.setColor(new Color(255,175,175));
	g.drawString("PINK: Color(255,175,175)", 30, 180);
	g.setColor(new Color(0,255,255));
	g.drawString("CYAN: Color(0,255,255)", 30, 210);
	g.setColor(new Color(255,0,255));
	g.drawString("MAGENTA: Color(255,0,255)", 30, 240);
	g.setColor(new Color(255,255,0));
	g.drawString("YELLOW: Color(255,255,0)", 30, 270);
	g.setColor(new Color(255,255,255));
	g.drawString("WHITE: Color(255,255,255)", 30, 300);
	g.setColor(new Color(128,128,128));
	g.drawString("GRAY: Color(128,128,128)", 30, 330);
	g.setColor(new Color(128,128,128));
	g.drawString("LIGHT_GRAY: Color(192,192,192)", 30, 360);
	g.setColor(new Color(64,64,64));
	g.drawString("DARK_GRAY: Color(64,64,64)", 30, 390);
	g.setColor(new Color(164,255,64));
	g.drawString("Color(164,255,64)", 30, 420);
    }

    /*
     * Main method that generates a frame and a colour panel.
     */
    public static void main(String[] args) { 
    	final int FRAME_WIDTH = 800;
    	final int FRAME_HEIGHT = 600;
    	Colour panel = new Colour();
    	JFrame frame = new JFrame();
    	frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    	frame.setSize(FRAME_WIDTH,FRAME_HEIGHT); 
	frame.add(panel);   
	frame.setVisible(true); // makes the application visible.
    }
}
